site_name: LocateIT Documentatie
nav:
    - Home: index.md
    - Afdeling: afdeling.md
    - Feedbacks: feedbacks.md
    - Products: products.md
    - Stocks: stocks.md
    - PeopleCounter: peoplecounter.md
    - Gebruikers: gebruikers.md
theme: readthedocs
